### ISSUE TITLE
Inventory system update

### ISSUE THREAD

**Issue by ultimateownsz** [ultimateownsz/PySeas#35]
Add upon the basic inventory system

- [ ] see how much "money" you have
- [ ] see what items you have in your inventory
- [ ] create a basic shop interaction (first create a basic shop system)

Extra
- [ ] able to sell items from your inventory to the shop
- [ ] able to trade with npc's you encounter (first create a basic npc system)

**Comment by PurpleProg** [comment]
that's UI features, they can come later i think. Maybe we should prioritize the main structure of the game, like the turn system.

**Comment by ultimateownsz** [comment]
Yes good call I will update this and make another issue on it!

**Comment by ultimateownsz** [comment]
This was an old issue, we changed this to user stories, you can see the new issues and acceptance criteria per user story on here:
https://github.com/users/ultimateownsz/projects/15/views/1
