### ISSUE TITLE
Basic User Interface

### ISSUE THREAD

**Issue by ultimateownsz** [ultimateownsz/PySeas#37]
Our main focus is now on the basic implementation and coding of all the systems that work together in order to make a basic game loop for the boardgame. We haven't decided on how the UI would look like and have to make this decision on the Discord server. If you are not part of our Discord yet, you can join it [here](https://discord.gg/MZ5MHqDnGW)

We will update this later on:
- [ ] task
- [ ] task

**Comment by AnSiChen** [comment]
Hello, I like this project and would like to work on it by adding features to improve the current version. Please let me know if the project if still going and if you guys are actively looking for contributions. Thank you!

**Comment by ultimateownsz** [comment]
This was an old issue, we changed this to user stories, you can see the new issues and acceptance criteria per user story on here:
https://github.com/users/ultimateownsz/projects/15/views/1
